Vấn đề 1: Tiến hành tải dữ liệu vào chương trình ứng dụng Python và giải quyết vấn đề "Missing header in the csv file"

In [99]:
import numpy as np # Gọi thư viện numpy gán np
import pandas as pd # Gọi thư viện pandas gán pd

In [100]:
patientheartrate = pd.read_csv('patient_heart_rate.csv') # Đọc dữ liệu file patient_heart_rate.csv
patientheartrate # Hiển thị dataframe

       1    Mickéy Mousé    56       70kgs   72   69   71    -  -.1  -.2
0    2.0     Donald Duck  34.0   154.89lbs    -    -    -   85   84   76
1    3.0      Mini Mouse  16.0         NaN    -    -    -   65   69   72
2    4.0  Scrooge McDuck   NaN       78kgs   78   79   72    -    -    -
3    5.0    Pink Panther  54.0  198.658lbs    -    -    -   69  NaN   75
4    6.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
5    7.0    Dewey McDuck  19.0       56kgs    -    -    -   71   78   75
6    8.0      Scööpy Doo  32.0       78kgs   78   76   75    -    -    -
7    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
8    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
9    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
10   9.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
11  10.0    Louie McDuck  12.0       45kgs    -    -    -   92   95   87
12  11.0       Henry Nam   NaN       60kgs   78   75   72    -    -    -
13  12.0     Michel Long  34.0         NaN   65   67   55    -    -    -
14  13.0      Tana Ricky   NaN         NaN    -    -    -   68   72   70
15  14.0        UniLever   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  15.0             NaN  52.0      180lbs    -    -    -   68   75   72

In [101]:
column_names=["ID", "Name", "Age", "Weight", "m0006", "m0612","m1218", "f0006", "f0612", "f1218"] # Thêm danh sách các tên cột
df = pd.read_csv('patient_heart_rate.csv', names = column_names)
# Đọc dữ liệu từ file patient_heart_rate.csv và gán tên cột từ danh sách column_names vào dataframe

In [102]:
df.head(5) # Hiển thị 5 hàng đầu tiên

    ID            Name   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218
0  1.0    Mickéy Mousé  56.0       70kgs    72    69    71     -     -     -
1  2.0     Donald Duck  34.0   154.89lbs     -     -     -    85    84    76
2  3.0      Mini Mouse  16.0         NaN     -     -     -    65    69    72
3  4.0  Scrooge McDuck   NaN       78kgs    78    79    72     -     -     -
4  5.0    Pink Panther  54.0  198.658lbs     -     -     -    69   NaN    75

Vấn đề 2: Xử lý vấn đề một cột lưu hỗn hợp nhiều dữ liệu, ở đây là cột "Name" chứa bao gồm "Firstname" và "Lastname", giải pháp là ta sẽ tách ra làm 2 cột

In [103]:
df[['Firstname', 'Lastname']]= df['Name'].str.split(expand = True)
# Tách cột Name thành hai cột Firstname và Lastname dựa trên khoảng trắng và thêm chúng vào dataframe.

In [104]:
# Xóa cột Name
df = df.drop('Name',axis=1)

In [105]:
df # Hiển thị dataframe

,ID,Age,Weight,m0006,m0612,m1218,f0006,f0612,f1218,Firstname,Lastname
0,1.0,56.0,70kgs,72,69,71,-,-,-,Mickéy,Mousé
1,2.0,34.0,154.89lbs,-,-,-,85,84,76,Donald,Duck
2,3.0,16.0,NaN,-,-,-,65,69,72,Mini,Mouse
3,4.0,NaN,78kgs,78,79,72,-,-,-,Scrooge,McDuck
4,5.0,54.0,198.658lbs,-,-,-,69,NaN,75,Pink,Panther
5,6.0,52.0,189lbs,-,-,-,68,75,72,Huey,McDuck
6,7.0,19.0,56kgs,-,-,-,71,78,75,Dewey,McDuck
7,8.0,32.0,78kgs,78,76,75,-,-,-,Scööpy,Doo
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,9.0,52.0,189lbs,-,-,-,68,75,72,Huey,McDuck
12,10.0,12.0,45kgs,-,-,-,92,95,87,Louie,McDuck
13,11.0,NaN,60kgs,78,75,72,-,-,-,Henry,Nam
14,12.0,34.0,NaN,65,67,55,-,-,-,Michel,Long
15,13.0,NaN,NaN,-,-,-,68,72,70,Tana,Ricky
16,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UniLever,None
17,15.0,52.0,180lbs,-,-,-,68,75,72,NaN,NaN

Vấn đề 3: Cột Weight có vấn đề về không thống nhất các đơn vị đo lường trong dữ liệu. Ta sẽ chuyển các đơn vị về thành đơn vị chuẩn "kg"

In [106]:
weight= df['Weight'] # Gán cột Weight vào biến weight

for i in range(0, len(weight)): # Gọi vòng lặp for lặp qua từng phần tử trong cột weight
    x = str(weight[i]) # Chuyển giá trị của phần tử weight[i] thành chuỗi
    if "lbs" in x[-3:]: # Nếu chuỗi x có chứa lbs ở ba ký tự cuối
        x = x[:-3:]# Loại bỏ lbs khỏi chuỗi x
        float_x = float(x) # Chuyển đổi x thành số thực
        y = int(float_x/2.2) # Chuyển đổi đơn vị từ pound sang kilogram bằng cách chia cho 2.2
        y = str(y) + "kgs" # Chuyển đổi kết quả sang chuỗi, thêm "kgs"
        weight[i] = y # Gán giá trị đã chuyển đổi lại cho phần tử tương ứng

C:\Users\Pc\AppData\Local\Temp\ipykernel_8012\2327792520.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y

In [107]:
df # Hiển thị dataframe

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
8    NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
9    NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
10   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
11   9.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

Vấn đề 4: Vấn đề về xuất hiện dòng dữ liệu rỗng (không có giá trị: NaN). Giải pháp có thể đưa ra là xóa bỏ

In [108]:
df.dropna(how= "all", inplace = True) # Xóa các hàng mà tất cả các giá trị là NaN.

In [109]:
df # Hiển thị dataframe

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
11   9.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

Vấn đề 5: Có nhiều dòng dữ liệu bị trùng lắp thông tin hoàn toàn[fullname, lastname, age, weight,....], giải pháp đưa ra là chỉ giữ lại một dòng dữ liệu, tuy nhiên giải pháp phải dựa trên nghiệp vụ của tập dữ liệu và quan sát của người xử lý.

In [110]:
df = df.drop_duplicates(subset=['Firstname','Lastname', 'Age', 'Weight']) # Loại bỏ các hàng trùng lặp dựa trên các cột Firstname, Lastname, Age và Weight.

In [111]:
df # Hiển thị dataframe

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

Vấn đề 6: Xuất hiện dữ liệu bị ảnh hưởng bởi lỗi non-ASCII, không định dạng ASCII. 
Giải pháp: Tùy vào nghiệp vụ ta có thể: xóa dữ liệu tại đó, thay thế bằng dữ liệu khác hoặc thay bằng việc đánh dấu bằng một kí tự khác (ví dụ: 'warning')

In [112]:
df.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True) 
# Thay thế các ký tự không thuộc bảng mã ASCII trong cột Firstname bằng chuỗi rỗng
df.Lastname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
# Thay thế các ký tự không thuộc bảng mã ASCII trong cột Lastname bằng chuỗi rỗng

C:\Users\Pc\AppData\Local\Temp\ipykernel_8012\25753429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
C:\Users\Pc\AppData\Local\Temp\ipykernel_8012\25753429.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Lastname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)

In [113]:
df # Hiển thị dataframe

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -      Scpy      Doo
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

Vấn đề 7: "Missing values", vấn đề này xảy ra tại các cột "Age", "Weight" và "Heart Rate". Thiếu dữ liệu (dữ liệu không đầy đủ) là vấn đề xảy ra nhiều trong các nguồn dữ liệu do nhiều nguyên nhân chủ quan lẫn khách quan.

Yêu cầu:
*   Thống kê thông tin dữ liệu thiếu trên từng biến Age và Weight  
    Yêu cầu xử lý dữ liệu thiếu như sau: Nếu dòng nào có Age hoặc Weight có dữ liệu thì phần Age hoặc Weight được tính như bên dưới, nếu thiếu cả 2 thông tin thì xóa dòng

In [114]:
index_ageweightnull = df[df['Age'].isna() & df['Weight'].isna()].index # Lấy chỉ số của các hàng mà cả hai cột Age và Weight có giá trị là NaN, gán vào biến index_ageweightnull
index_ageweightnull # Hiển thị index_ageweightnull

Int64Index([15, 16], dtype='int64')

In [115]:
df.drop(index_ageweightnull, inplace=True) # Xóa các hàng trong index_ageweightnull

C:\Users\Pc\AppData\Local\Temp\ipykernel_8012\1033412771.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(index_ageweightnull, inplace=True)

In [116]:
df['Age'].fillna(df['Age'].mean(), inplace =False) # Điền giá trị NaN trong cột Age bằng giá trị trung bình của cột Age

0     56.0
1     34.0
2     16.0
3     36.1
4     54.0
5     52.0
6     19.0
7     32.0
12    12.0
13    36.1
14    34.0
17    52.0
Name: Age, dtype: float64

Vấn đề 8: "Một cột chứa quá nhiều thông tin cần được phân rã", như trong bài toán này ta thấy header "m0006" chứa các nội dung bao gồm: m -> male, 1218 ~ 12-18 (mm-dd). 
Còn giá trị thì là kết quả huyết áp.

In [117]:
df = pd.melt(df, id_vars=['ID', 'Age', 'Weight', 'Firstname', 'Lastname'], value_name="PulseRate", var_name="sex_and_time").sort_values(['ID', 'Age', 'Weight', 'Firstname', 'Lastname'])
# Chuyển đổi df phân rã, giữ các cột ID, Age, Weight, Firstname và Lastname làm các cột nhận diện và chuyển các cột còn lại thành hai cột sex_and_time và PulseRate, sắp xếp df dựa trên các cột ID, Age, Weight, Firstname và Lastname

In [118]:
len(df['PulseRate']) # Đếm số lượng phần tử trong cột PulseRate

72

In [119]:
df.head(10) # Hiển thị 10 hàng đầu tiên

     ID   Age Weight Firstname Lastname sex_and_time PulseRate
0   1.0  56.0  70kgs     Micky     Mous        m0006        72
12  1.0  56.0  70kgs     Micky     Mous        m0612        69
24  1.0  56.0  70kgs     Micky     Mous        m1218        71
36  1.0  56.0  70kgs     Micky     Mous        f0006         -
48  1.0  56.0  70kgs     Micky     Mous        f0612         -
60  1.0  56.0  70kgs     Micky     Mous        f1218         -
1   2.0  34.0  70kgs    Donald     Duck        m0006         -
13  2.0  34.0  70kgs    Donald     Duck        m0612         -
25  2.0  34.0  70kgs    Donald     Duck        m1218         -
37  2.0  34.0  70kgs    Donald     Duck        f0006        85

In [120]:
tmp_df= df["sex_and_time"].str.extract("(\D)(\d+)(\d{2})", expand=True) # Tách giá trị trong cột sex_and_time thành ba cột mới dựa trên biểu thức: cột đầu tiên chứa các ký tự chữ (\D), cột thứ hai chứa các chữ số (\d+), cột thứ ba chứa hai chữ số cuối (\d{2})

In [121]:
tmp_df.columns=["Sex", "hours_lower", "hours_upper"] # Đặt tên cho cột của tmp_df là Sex, hours_lower và hours_upper

In [122]:
tmp_df["Time"]= tmp_df["hours_lower"] + "-" + tmp_df["hours_upper"]
# Tạo cột mới Time trong tmp_df bằng cách kết hợp giá trị của hai cột hours_lower và hours_upper với dấu gạch ngang ở giữa

In [123]:
df = pd.concat([df, tmp_df], axis=1) # Kết hợp df và tmp_df theo các cột

In [124]:
df = df.drop(['sex_and_time','hours_lower','hours_upper'], axis=1)
# Xóa các cột sex_and_time, hours_lower và hours_upper khỏi df.
df = df.dropna() # Xóa các hàng có giá trị NaN trong df

In [125]:
df.head(10) # Hiển thị 10 hàng đầu tiên

     ID   Age Weight Firstname Lastname PulseRate Sex   Time
0   1.0  56.0  70kgs     Micky     Mous        72   m  00-06
12  1.0  56.0  70kgs     Micky     Mous        69   m  06-12
24  1.0  56.0  70kgs     Micky     Mous        71   m  12-18
36  1.0  56.0  70kgs     Micky     Mous         -   f  00-06
48  1.0  56.0  70kgs     Micky     Mous         -   f  06-12
60  1.0  56.0  70kgs     Micky     Mous         -   f  12-18
1   2.0  34.0  70kgs    Donald     Duck         -   m  00-06
13  2.0  34.0  70kgs    Donald     Duck         -   m  06-12
25  2.0  34.0  70kgs    Donald     Duck         -   m  12-18
37  2.0  34.0  70kgs    Donald     Duck        85   f  00-06

In [126]:
df.to_csv('outputcleanup.csv',index=False) # Lưu dataframe vào file outputcleanup.csv
df # Hiển thị dataframe

      ID   Age Weight Firstname Lastname PulseRate Sex   Time
0    1.0  56.0  70kgs     Micky     Mous        72   m  00-06
12   1.0  56.0  70kgs     Micky     Mous        69   m  06-12
24   1.0  56.0  70kgs     Micky     Mous        71   m  12-18
36   1.0  56.0  70kgs     Micky     Mous         -   f  00-06
48   1.0  56.0  70kgs     Micky     Mous         -   f  06-12
60   1.0  56.0  70kgs     Micky     Mous         -   f  12-18
1    2.0  34.0  70kgs    Donald     Duck         -   m  00-06
13   2.0  34.0  70kgs    Donald     Duck         -   m  06-12
25   2.0  34.0  70kgs    Donald     Duck         -   m  12-18
37   2.0  34.0  70kgs    Donald     Duck        85   f  00-06
49   2.0  34.0  70kgs    Donald     Duck        84   f  06-12
61   2.0  34.0  70kgs    Donald     Duck        76   f  12-18
4    5.0  54.0  90kgs      Pink  Panther         -   m  00-06
16   5.0  54.0  90kgs      Pink  Panther         -   m  06-12
28   5.0  54.0  90kgs      Pink  Panther         -   m  12-18
40   5.0  54.0  90kgs      Pink  Panther        69   f  00-06
64   5.0  54.0  90kgs      Pink  Panther        75   f  12-18
5    6.0  52.0  85kgs      Huey   McDuck         -   m  00-06
17   6.0  52.0  85kgs      Huey   McDuck         -   m  06-12
29   6.0  52.0  85kgs      Huey   McDuck         -   m  12-18
41   6.0  52.0  85kgs      Huey   McDuck        68   f  00-06
53   6.0  52.0  85kgs      Huey   McDuck        75   f  06-12
65   6.0  52.0  85kgs      Huey   McDuck        72   f  12-18
6    7.0  19.0  56kgs     Dewey   McDuck         -   m  00-06
18   7.0  19.0  56kgs     Dewey   McDuck         -   m  06-12
30   7.0  19.0  56kgs     Dewey   McDuck         -   m  12-18
42   7.0  19.0  56kgs     Dewey   McDuck        71   f  00-06
54   7.0  19.0  56kgs     Dewey   McDuck        78   f  06-12
66   7.0  19.0  56kgs     Dewey   McDuck        75   f  12-18
7    8.0  32.0  78kgs      Scpy      Doo        78   m  00-06
19   8.0  32.0  78kgs      Scpy      Doo        76   m  06-12
31   8.0  32.0  78kgs      Scpy      Doo        75   m  12-18
43   8.0  32.0  78kgs      Scpy      Doo         -   f  00-06
55   8.0  32.0  78kgs      Scpy      Doo         -   f  06-12
67   8.0  32.0  78kgs      Scpy      Doo         -   f  12-18
8   10.0  12.0  45kgs     Louie   McDuck         -   m  00-06
20  10.0  12.0  45kgs     Louie   McDuck         -   m  06-12
32  10.0  12.0  45kgs     Louie   McDuck         -   m  12-18
44  10.0  12.0  45kgs     Louie   McDuck        92   f  00-06
56  10.0  12.0  45kgs     Louie   McDuck        95   f  06-12
68  10.0  12.0  45kgs     Louie   McDuck        87   f  12-18

11. Hãy khảo sát tỉ lệ dữ liệu thiếu trên biến huyết áp.

In [127]:
df['PulseRate']= df['PulseRate'].replace({'-' : '0'}, regex=True) 
# Thay thế ký tự '-' bằng 0 trong cột PulseRate
df["PulseRate"].fillna('0', inplace =True) # Điền giá trị 0 cho giá trị bị thiếu trong cột PulseRate

In [128]:
# Tính toán trung bình của các giá trị huyết áp của nhóm giới tính
def avgPulseRateBySex(df, sex): # Hàm để tính trung bình PulseRate theo sex
    sumPulseRate = 0 # Khởi tạo tổng giá trị PulseRate bằng 0
    nsumPulseRate = 0 # Khởi tạo số lượng giá trị PulseRate bằng 0
    for i, value in enumerate(df['Sex']): # Lặp qua từng giá trị trong cột Sex
        if value == sex: # Nếu giá trị giới tính của hàng hiện tại bằng sex
            try:
                if df['PulseRate'][i] != '0': # Nếu giá trị PulseRate khác 0
                    sumPulseRate += int(df['PulseRate'].values[i]) # Cộng giá trị PulseRate vào sumPulseRate
                    nsumPulseRate += 1  # Tăng số lượng các giá trị thêm 1
            except:
                pass 
    if nsumPulseRate > 0: # Nếu có ít nhất một giá trị PulseRate
        return str(sumPulseRate / nsumPulseRate) # Trả về giá trị trung bình của PulseRate dạng chuỗi
    else: # nếu không có
        return 0 # Trả về 0

In [129]:
# Tính toán trung bình huyết áp của các giá trị dữ liệu
def avgPulseRateOverall(df): # Hàm để tính trung bình PulseRate cho dữ liệu df
    sumPulseRate = 0 # Khởi tạo tổng giá trị PulseRate bằng 0
    nsumPulseRate = 0 # Khởi tạo số lượng giá trị PulseRate bằng 0
    for i, value in enumerate(df['PulseRate']): # Lặp qua từng giá trị trong cột PulseRate
        try:
            if value != '0': # Nếu giá trị PulseRate khác 0
                sumPulseRate += int(value) # Cộng giá trị PulseRate vào sumPulseRate
                nsumPulseRate += 1  # Tăng số lượng các giá trị thêm 1
        except:
            pass
    if nsumPulseRate > 0: # Nếu có ít nhất một giá trị PulseRate
        return str(sumPulseRate / nsumPulseRate)  # Trả về giá trị trung bình của PulseRate dạng chuỗi
    else: # nếu không có
        return 0 # Trả về 0

In [130]:
def avgPulserate(df, firstname): # Hàm để tính trung bình PulseRate theo firstname
    sumPulserate = 0 # Khởi tạo tổng giá trị PulseRate bằng 0
    nsumPulserate = 0 # Khởi tạo số lượng giá trị PulseRate bằng 0
    for i, value in enumerate(df['Firstname']): # Lặp qua từng giá trị trong cột Firstname
        if value == firstname: # Nếu giá trị Firstname của hàng hiện tại bằng với firstname 
            try:
                if df['PulseRate'][i] !='0': # Nếu giá trị PulseRate khác 0
                    sumPulserate += int(df['PulseRate'].values[i]) # Cộng giá trị PulseRate vào sumPulseRate
                    nsumPulserate += 1 # Tăng số lượng các giá trị thêm 1
            except:
                pass
    if nsumPulserate > 0: # Nếu có ít nhất một giá trị PulseRate
        return str(sumPulserate/nsumPulserate)  # Trả về giá trị trung bình của PulseRate dạng chuỗi
    else: # nếu không có
        return 0 # Trả về 0

In [131]:
def isValidIndex1(index, nrows): # Hàm kiểm tra chỉ số hợp lệ trong phạm vi df
    return index - 1 > 0 & index + 1 < nrows # Trả về True nếu chỉ số nằm trong phạm vi hợp lệ, ngược lại trả về False

In [132]:
def isValidIndex2(index, nrows): # Hàm kiểm tra chỉ số hợp lệ trong phạm vi df
  return index + 1 < nrows & index + 2 < nrows # Trả về True nếu chỉ số nằm trong phạm vi hợp lệ, ngược lại trả về False

In [133]:
def isPulseRateNotNull1(index, df): # Hàm kiểm tra giá trị PulseRate không phải 0
  return str(df['PulseRate'].values[index-1])!= '0' and str(df['PulseRate'].values[index+1])!= '0' # Trả về True nếu giá trị PulseRate của hai hàng xung quanh không phải 0, ngược lại trả về False

In [134]:
def isPulseRateNotNull2(index, df): # Hàm kiểm tra giá trị PulseRate không phải 0
  return str(df['PulseRate'].values[index+1])!= '0' and str(df['PulseRate'].values[index +2])!= '0' # Trả về True nếu giá trị PulseRate của hai hàng kế tiếp không phải 0, ngược lại trả về False

In [135]:
def isInGroup1(df, index, firstname): #  Hàm kiểm tra giá trị Firstname của hai hàng xung quanh có giống nhau không
  return df['Firstname'].values[index-1]== firstname and df['Firstname'].values[index +1]== firstname # ^rả về True nếu giá trị Firstname của hai hàng xung quanh giống nhau, ngược lại trả về False

In [136]:
def isInGroup2(df, index, firstname): # Hàm kiểm tra giá trị Firstname của hai hàng kế tiếp có giống nhau không
  return df['Firstname'].values[index+1]== firstname and df['Firstname'].values[index +2]== firstname # Trả về True nếu giá trị Firstname của hai hàng kế tiếp giống nhau, ngược lại trả về False

In [137]:
def updatePulseRatena(index, df): # Hàm cập nhật giá trị PulseRate
    nrows = len(df['PulseRate']) - 2 # Lấy số lượng hàng trong df trừ 2
    newvalue = '' # Khởi tạo giá trị mới rỗng
    firstname = df['Firstname'].values[index] # Lấy giá trị Firstname của hàng hiện tại
    sex = df['Sex'].values[index] # Lấy giá trị Sex của hàng hiện tại
    try:
        if isValidIndex1(index, nrows) and isPulseRateNotNull1(index, df) and isInGroup1(df, index, firstname): # Nếu chỉ số hợp lệ và giá trị PulseRate của hai hàng xung quanh không phải 0 và giá trị Firstname của hai hàng xung quanh giống nhau
            try:
                newvalue = (int(df['PulseRate'].values[index - 1]) + int(df['PulseRate'].values[index + 1])) / 2 # Trung bình giá trị PulseRate của 2 hàng xung quanh
            except:
                newvalue = '0' # Gán giá trị newvalue là 0
        elif isValidIndex2(index, nrows) and isPulseRateNotNull2(index, df) and isInGroup2(df, index, firstname): # Nếu chỉ số hợp lệ và giá trị PulseRate của hai hàng kế tiếp không phải 0 và giá trị Firstname của hai hàng kế tiếp giống nhau
            try:
                newvalue = (int(df['PulseRate'].values[index + 1]) + int(df['PulseRate'].values[index + 2])) / 2 # Trung bình giá trị PulseRate của 2 hàng kế tiếp
            except:
                newvalue = '0' # Gán giá trị newvalue là 0
        else:
            newvalue = avgPulserate(df, firstname) # Lấy trung bình giá trị PulseRate của người đó
            if newvalue == '0': # Nếu giá trị trung bình Pulserate của người đó là 0
                newvalue = avgPulseRateBySex(df, sex) # Lấy trung bình giá trị PulseRate theo sex
                if newvalue == '0': # Nếu giá trị trung bình sex của người đó là 0
                    newvalue = avgPulseRateOverall(df) # Lấy trung bình giá trị PulseRate
    except:
        newvalue = avgPulserate(df, firstname) # Lấy trung bình giá trị PulseRate của người đó
        if newvalue == '0': # Nếu giá trị trung bình Pulserate của người đó là 0
            newvalue = avgPulseRateBySex(df, sex) # Lấy trung bình giá trị PulseRate theo sex
            if newvalue == '0': # Nếu giá trị trung bình sex của người đó là 0
                newvalue = avgPulseRateOverall(df) # Lấy trung bình giá trị PulseRate
    return newvalue # Trả về giá trị newvalue

In [139]:
pulserateupdate = [] # Khởi tạo danh sách rỗng để lưu các giá trị PulseRate được cập nhật
for index, value in enumerate(df["PulseRate"]): # Lặp qua từng giá trị và chỉ số trong cột PulseRate
  if value =='0' or value == '': # Nếu giá trị PulseRate = 0 hoặc bị thiếu
    newvalue = updatePulseRatena(index,df) # Cập nhật giá trị PulseRate
    pulserateupdate.append(newvalue) # Thêm giá trị PulseRate được cập nhật vào danh sách pulserateupdate
  else:
    pulserateupdate.append(value) # Thêm giá trị PulseRate hiện tại vào danh sách pulserateupdate

In [140]:
df["PulseRateUpdate"] = pulserateupdate # Thêm cột PulseRateUpdate vào dataframe
df # Hiển thị dataframe

      ID   Age Weight Firstname Lastname PulseRate Sex   Time PulseRateUpdate
0    1.0  56.0  70kgs     Micky     Mous        72   m  00-06              72
12   1.0  56.0  70kgs     Micky     Mous        69   m  06-12              69
24   1.0  56.0  70kgs     Micky     Mous        71   m  12-18              71
36   1.0  56.0  70kgs     Micky     Mous         0   f  00-06            72.0
48   1.0  56.0  70kgs     Micky     Mous         0   f  06-12            72.0
60   1.0  56.0  70kgs     Micky     Mous         0   f  12-18            72.0
1    2.0  34.0  70kgs    Donald     Duck         0   m  00-06             0.0
13   2.0  34.0  70kgs    Donald     Duck         0   m  06-12             0.0
25   2.0  34.0  70kgs    Donald     Duck         0   m  12-18             0.0
37   2.0  34.0  70kgs    Donald     Duck        85   f  00-06              85
49   2.0  34.0  70kgs    Donald     Duck        84   f  06-12              84
61   2.0  34.0  70kgs    Donald     Duck        76   f  12-18              76
4    5.0  54.0  90kgs      Pink  Panther         0   m  00-06             0.0
16   5.0  54.0  90kgs      Pink  Panther         0   m  06-12             0.0
28   5.0  54.0  90kgs      Pink  Panther         0   m  12-18             0.0
40   5.0  54.0  90kgs      Pink  Panther        69   f  00-06              69
64   5.0  54.0  90kgs      Pink  Panther        75   f  12-18              75
5    6.0  52.0  85kgs      Huey   McDuck         0   m  00-06             0.0
17   6.0  52.0  85kgs      Huey   McDuck         0   m  06-12             0.0
29   6.0  52.0  85kgs      Huey   McDuck         0   m  12-18             0.0
41   6.0  52.0  85kgs      Huey   McDuck        68   f  00-06              68
53   6.0  52.0  85kgs      Huey   McDuck        75   f  06-12              75
65   6.0  52.0  85kgs      Huey   McDuck        72   f  12-18              72
6    7.0  19.0  56kgs     Dewey   McDuck         0   m  00-06             0.0
18   7.0  19.0  56kgs     Dewey   McDuck         0   m  06-12             0.0
30   7.0  19.0  56kgs     Dewey   McDuck         0   m  12-18             0.0
42   7.0  19.0  56kgs     Dewey   McDuck        71   f  00-06              71
54   7.0  19.0  56kgs     Dewey   McDuck        78   f  06-12              78
66   7.0  19.0  56kgs     Dewey   McDuck        75   f  12-18              75
7    8.0  32.0  78kgs      Scpy      Doo        78   m  00-06              78
19   8.0  32.0  78kgs      Scpy      Doo        76   m  06-12              76
31   8.0  32.0  78kgs      Scpy      Doo        75   m  12-18              75
43   8.0  32.0  78kgs      Scpy      Doo         0   f  00-06            75.0
55   8.0  32.0  78kgs      Scpy      Doo         0   f  06-12            75.0
67   8.0  32.0  78kgs      Scpy      Doo         0   f  12-18            75.0
8   10.0  12.0  45kgs     Louie   McDuck         0   m  00-06            43.5
20  10.0  12.0  45kgs     Louie   McDuck         0   m  06-12            43.5
32  10.0  12.0  45kgs     Louie   McDuck         0   m  12-18            43.5
44  10.0  12.0  45kgs     Louie   McDuck        92   f  00-06              92
56  10.0  12.0  45kgs     Louie   McDuck        95   f  06-12              95
68  10.0  12.0  45kgs     Louie   McDuck        87   f  12-18              87

12. Hãy rút gọn dữ liệu phù hợp và reindex lại dữ liệu. Sau đó, lưu trữ dữ liệu đã xử lý thành công với tên file patient_heart_rate_clean.csv

In [141]:
# Reindex lại dataframe
df_cleaned = df[['Firstname', 'Sex', 'PulseRateUpdate']].copy()  # Giữ lại các cột cần thiết
df_cleaned = df_cleaned.reset_index(drop=True)  # Đặt lại chỉ số cho dataframe

# Lưu file patient_heart_rate_clean.csv
df_cleaned.to_csv('patient_heart_rate_clean.csv', index=False)  

# Hiển thị thông báo
print("Lưu thành công")

Lưu thành công